{
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=.;Database=Database;User Id=sa; Password=123;"
  },
  "JwtIssuerOptions": {
    "key": "C34A0D0214F14106AC04BA4410F23D12098F40DD973943ABF0D3756A2EEDAEC",
    "issuer": "http://localhost:4200/",
    "audience": "http://localhost:4200/",
    "expirationTime": 200
  },
  "AllowedOrigin": {
    "localHost": "http://localhost:4200"
  },
  "ExceptionSettings": {
    "ShowCustomMessage": true,
    "CustomMessage": "An unexpected error ocurred. Please, try again."
  }
}